CREATE TABLE categories(
    id          INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    name        VARCHAR(100) NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP on UPDATE CURRENT_TIMESTAMP
)CHARSET=utf8;